version: "3"
services:
  web:
    build:
      args:
        - SECRET_KEY_BASE=bf44d14d7d1436b502bb614689e4f1331bdbaa4496e5b1bd6c813cb1932f3fd6b50b579169280afb9a759549ac288be9458a3dcd69d5f492e99a10ac1eb7ac8e
      context: .
      dockerfile: Dockerfile.prod
    command:
      [
        "/wait/wait-for-postgres.sh",
        "database",
        "bin/rails",
        "s",
        "-b",
        "0.0.0.0",
        "-p",
        "80"
      ]
    env_file:
      - .env/production/database
      - .env/production/web
    ports:
      - "80:80"
